# Generated by Django 2.0.6 on 2018-06-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foursquarevenue',
            name='latitude',
            field=models.DecimalField(decimal_places=20, max_digits=20),
        ),
        migrations.AlterField(
            model_name='foursquarevenue',
            name='longitude',
            field=models.DecimalField(decimal_places=20, max_digits=20),
        ),
    ]
