# Generated by Django 2.0.6 on 2018-06-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20180618_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='foursquarevenue',
            name='request_id',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foursquarevenue',
            name='visited',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
